"""empty message

Revision ID: b7a4429b7cc7
Revises: 6f77f218806e
Create Date: 2020-10-15 23:13:11.404960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a4429b7cc7'
down_revision = '6f77f218806e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'content', ['id'])
    op.add_column('posts', sa.Column('title', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'posts', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'title')
    op.drop_constraint(None, 'content', type_='unique')
    # ### end Alembic commands ###
